### ISSUE TITLE
Change images

### ISSUE THREAD

**Issue by MasterChief1335** [mzashh/HUB75-Pixel-Art-Display#9]
Hi how Change i the Images?

and will there be an update for this?

thx

**Comment by mzashh** [comment]
By "Change the images," I assume you mean play new GIFs. To change the GIFs, go to the web UI via the IP displayed during the boot, upload a new GIF, and once it's uploaded, click on Play. 

As for updates, I do have some things planned, but due to a lack of time, I am unable to work on them currently. 

Also, please stop opening new issues, you can comment on the ones you have previously created.

**Comment by MasterChief1335** [comment]
Yes, if I have several pictures that switch through.

ok. would be cool.

OK. thought for each problem separate post

**Comment by mzashh** [comment]
The problems you're facing aren't issues with the firmware, you simply didn't bother to read the [Misc section](https://github.com/mzashh/HUB75-Pixel-Art-Display?tab=readme-ov-file#firmware).

To play multiple files one after the other, uncomment lines [411-413](https://github.com/mzashh/HUB75-Pixel-Art-Display/blob/main/firmware/firmware.ino#L411), and it should cycle through the GIFs:

`dma_display->fillScreen(dma_display->color565(0, 0, 0));`
`gifFile.close();`
`gifFile = root.openNextFile();`

This will ensure the files play sequentially.

**Comment by MasterChief1335** [comment]
ok changes through but I animated gif and not animated the cycle varies between animated and not.
can you adjust this? thx

**Comment by MasterChief1335** [comment]
ok changes through but I animated gif and not animated the cycle varies between animated and not.
can you adjust this? thx
